name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install aiogram requests aiohttp-socks
    
    - name: Build EXE
      run: pyinstaller --onefile --noconsole bot.py
    
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: MozgBot
        path: dist/bot.exe
